experiment:
  name: "diary_personal_finetuning"
  models_to_train: ["non_reasoning", "reasoning"]
  benchmarks_to_run: ["gsm8k", "hellaswag", "arc_easy", "social_iqa", "truthfulqa", "winogrande", "hendrycks_ethics", "mmlu_subset"]
  save_results_to: "./experiment_results"

# THIS WAS MISSING - Data configuration
data:
  source: "json"  # or "json"
  mongodb_uri: "mongodb://localhost:27017/"
  json_path: "../data/exported_diary_data_10000.json"
  test_size: 50
  validation_split: 0.2
  max_length: 2048

# Evaluation configuration  
evaluation:
  batch_size: 4
  num_fewshot: 0  # Zero-shot for pure model comparison
  timeout: 1800
  output_dir: "./eval_results"

wandb:
  project: "finetune-my-diary"
  entity: "akashe"  
  tags: ["diary", "personal-data", "fine-tuning"]