# configs/non_reasoning.yaml
model:
  name: "non_reasoning"
  base_model: "microsoft/DialoGPT-medium"
  max_seq_length: 2048
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]

training:
  output_dir: "./outputs"
  max_steps: 500
  learning_rate: 2e-4
  batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 50
  logging_steps: 10
  save_steps: 100
  eval_steps: 100
  load_in_4bit: true