# S3 Configuration
s3:
  bucket_name: "diary-training-artificats"
  aws_profile: null  # Use default AWS credentials, or specify profile name

  # Upload settings
  auto_upload: true  # Automatically upload after training
  upload_merged_models: true  # Upload fast inference models
  upload_lora_adapters: true  # Upload LoRA adapters as backup
  upload_evaluation_results: true  # Upload benchmark results
  upload_training_logs: true  # Upload wandb/training logs

  compress_logs: true  # Compress log files before upload
